# Generated by Django 2.1.4 on 2019-08-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentBrowsers',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('num_sites_visited', models.IntegerField()),
            ],
            options={
                'db_table': 'frequent_browsers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'people',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_visited', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'visits',
                'managed': False,
            },
        ),
    ]
